[default_session]
preview_command = "eza --all --git --icons --color=always {}"
# î¬†
# ó°¹¡
# ó°©
# ó°’ 
# ï’©
# ó°¢›
# îš›
# ó°£€

[[session]]
name = "î¬† HOME"
path = "~/"

[[session]]
name = "ó°¹¡ RUST KILLER"
startup_command = "ssh rust-killer tmux new-session -A -s main"

[[session]]
name = "ó°° LATTICA"
path = "~/Developer/lattica/core"
# startup_command = "tmux rename-window core && nvim"
# windows = ["frontend", "polymorph", "amm", "vy-ctf"]

[[session]]
name = "â”œâ”€â”€ ó°ˆ™ WHITEPAPER"
path = "~/Developer/lattica/docs/"
startup_command = "tmux rename-session 'ó°ˆ™ WHITEPAPER'"

[[session]]
name = "â”œâ”€â”€ ï‘± CORE"
path = "~/Developer/lattica/core/"
startup_command = "tmux rename-session 'ï‘± CORE' && nvim"

[[session]]
name = "â”œâ”€â”€ ï’© FRONTEND"
path = "~/Developer/lattica/frontend/"
startup_command = "tmux rename-session 'ï’© FRONTEND' && nvim"

[[session]]
name = "â”œâ”€â”€ ó°Ÿ¥ POLYMORPH"
path = "~/Developer/lattica/polymorph/"
startup_command = "tmux rename-session 'ó°Ÿ¥ POLYMORPH' && nvim"

[[session]]
name = "â”œâ”€â”€ ğ€ğ¯ó°•Î»ğ¯ AMM"
path = "~/Developer/lattica/amm/"
startup_command = "tmux rename-session 'ğ€ğ¯ó°•Î»ğ¯ AMM' && nvim"

[[session]]
name = "â•°â”€â”€ ïˆ CTF"
path = "~/Developer/lattica/vy-ctf/"
startup_command = "tmux rename-session 'ïˆ CTF' && nvim"

[[session]]
name = "î˜« NEOVIM"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "ó°© PHYT.FUN"
path = "~/Developer/phyt.fun"
startup_command = "nvim"

[[session]]
name = "ó°¢› ANVIL"
path = "~/Developer/lattica/"
startup_command = "anvil"

[[session]]
name = "îš› LATEX"
path = "~/Papers/"
# startup_command = "nvim"

[[session]]
name = "ó°£€ VOYAGER-1"
startup_command = "ssh voyager-1 tmux new-session -A -s main"

[[session]]
name = "ó°£€ PM-PROM-GRAF"
startup_command = "ssh polymorph-pm-gr tmux new-session -A -s main"

[[window]]
name = "frontend"
path = "~/Developer/lattica/frontend"
startup_script = "nvim"

[[window]]
name = "polymorph"
path = "~/Developer/lattica/polymorph"
startup_script = "nvim"

[[window]]
name = "amm"
path = "~/Developer/lattica/amm"
startup_script = "nvim"

[[window]]
name = "vy-ctf"
path = "~/Developer/lattica/vy-ctf/"
startup_script = "nvim"

[[window]]
name = "anysphere"
path = "~/Developer/anysphere-dark.nvim"
startup_script = "nvim"

[[window]]
name = "nvim"
path = "~/.config/nvim"
startup_script = "nvim"
