[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = " HOME"
path = "~/"

[[session]]
name = "󰹡 RUST KILLER"
startup_command = "ssh rust-killer tmux new-session -A -s main"

[[session]]
name = " NEOVIM"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "󰍩 PHYT.FUN"
path = "~/Developer/phyt.fun"
startup_command = "nvim ."

[[session]]
name = "󰒠 LATTICA"
path = "~/Developer/lattica/core"
startup_command = "tmux rename-window core && nvim ."
windows = ["frontend", "polymorph", "amm", "vy-ctf"]

[[session]]
name = "󰢛 ANVIL"
path = "~/Developer/lattica/"
startup_command = "anvil"

[[session]]
name = " LATEX"
path = "~/Papers/"
startup_command = "nvim ."

[[session]]
name = "󰣀 VOYAGER-1"
startup_command = "ssh voyager-1 tmux new-session -A -s main"

[[window]]
name = "frontend"
path = "~/Developer/lattica/frontend"
startup_script = "nvim ."

[[window]]
name = "polymorph"
path = "~/Developer/lattica/polymorph"
startup_script = "nvim ."

[[window]]
name = "amm"
path = "~/Developer/lattica/amm"
startup_script = "nvim ."

[[window]]
name = "vy-ctf"
path = "~/Developer/lattica/vy-ctf/"
startup_script = "nvim ."

[[window]]
name = "anysphere"
path = "~/Developer/anysphere-dark.nvim"
startup_script = "nvim ."

[[window]]
name = "nvim"
path = "~/.config/nvim"
startup_script = "nvim ."
