[general]
# import = ["~/.config/alacritty/anysphere.toml"]
import = ["~/.config/alacritty/mellow.toml"]
live_config_reload = true

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
dynamic_title = true
# opacity = 0.75
# blur = true

[font]
size = 18
# size = 10  # For ss's
offset = { x = 1, y = 13 }
# glyph_offset = { x = 0, y = 0 }
# offset = { x = 2, y = 2 }

[font.normal]
# family = "BlexMono Nerd Font Propo"
# style = "Regular"

# family = "MesloLGL Nerd Font"

family = "Hack Nerd Font"

# family = "Maple Mono NF"
# style = "Regular"

# family = "MonoLisa"
# style = "MonoLisa"

# family = "JetBrainsMono Nerd Font"
# style = "Regular"
#
# family = "CaskaydiaCove Nerd Font"
# style = "Regular"

# family = "SauceCodePro Nerd Font"
# style = "Medium"

[colors.primary]
background = "#131316"

[env]
TERM = "xterm-256color"
option_as_alt = "both"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"  # ESC + b (backward word)

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"  # ESC + f (forward word)

[[keyboard.bindings]]
key = "Up"
mods = "Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "Down"
mods = "Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "M"
mods = "Command"
chars = "\u001bm"

# --- WezTerm-like "tabs" (tmux windows) ---
[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0014"  # C-t

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0017"  # C-w

# ⌘ 1..⌘ 9/⌘ 0 -> M-1..M-0
[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u001b2"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u001b3"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u001b4"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u001b5"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u001b6"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u001b7"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u001b8"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u001b9"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
chars = "\u001b0"

# ⌘ ⇧ ] / ⌘ ⇧ [
# [[keyboard.bindings]]
# key = "]"
# mods = "Command|Shift"
# chars = "\u001bn"

[[keyboard.bindings]]
key = "["
mods = "Command"
chars = "\u001bp"

# ⌘H/J/K/L + U/D -> vim-aware navigation
[[keyboard.bindings]]
key = "H"
mods = "Command"
chars = "\u0008"  # C-h

[[keyboard.bindings]]
key = "J"
mods = "Command"
chars = "\u000A"  # C-j

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u000B"  # C-k

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u000C"  # C-l

[[keyboard.bindings]]
key = "U"
mods = "Command"
chars = "\u0015"  # C-u

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0004"  # C-d

# Session tree / reload / command prompt / detach
[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u001bs"

[[keyboard.bindings]]
key = "I"
mods = "Command"
chars = "\u001bi"

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u001bo"

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"
chars = "\u001b[78;6u"

[[keyboard.bindings]]
key = "R"
mods = "Command"
chars = "\u001br"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Command"
chars = "\u001b:"

# Deprecated tmux detach keybind
# [[keyboard.bindings]]
# key = "D"
# mods = "Command"
# chars = "\u001bd"

# New tmux detach keybind
[[keyboard.bindings]]
key = "X"
mods = "Command"
chars = "\u001bx"

# Splits (send M-\ and M--)
[[keyboard.bindings]]
key = "Backslash"
mods = "Command"
chars = "\u001b|"  # ESC + |

# Meta + MINUS for ⌘ -
[[keyboard.bindings]]
key = "Minus"
mods = "Command"
chars = "\u001b-"

# TOP split (new): ⌘ ⇧ -
[[keyboard.bindings]]
key = "Minus"
mods = "Command|Shift"
chars = "\u001b_"

# Resizing with ⌘⇧H/J/K/L (send M-H/J/K/L)
[[keyboard.bindings]]
key = "H"
mods = "Command|Shift"
chars = "\u001bH"

[[keyboard.bindings]]
key = "J"
mods = "Command|Shift"
chars = "\u001bJ"

[[keyboard.bindings]]
key = "K"
mods = "Command|Shift"
chars = "\u001bK"

[[keyboard.bindings]]
key = "L"
mods = "Command|Shift"
chars = "\u001bL"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"

# Outside of tmux, send '__SUPER_S__' to open sesh fzf
[[keyboard.bindings]]
key = "S"
mods = "Shift|Control|Alt"
chars = "__SUPER_S__"
